force-app/main/default/objects/Opportunity_Scoring_Rule__c/Opportunity_Scoring_Rule__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Rules that calculate a score for an opportunity</description>
    <label>Opportunity Scoring Rule</label>
</CustomObject>

force-app/main/default/objects/Opportunity_Scoring_Rule__c/fields/Implementing_Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Implementing_Class_Name__c</fullName>
    <label>Implementing Class Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RuleTestFixtures.cls
@isTest
public class RuleTestFixtures 
{
    public static Opportunity_Scoring_Rule__c GetRule(Integer idx,
                                                      String className)
    {
        Opportunity_Scoring_Rule__c rule=
                new Opportunity_Scoring_Rule__c(Index__c=idx,
                                                Implementing_Class_Name__c=className);

        return rule;
    }
}